### ISSUE TITLE
Rearchitect parent position propagation

### ISSUE THREAD

**Issue by MonkeyBars3k** [MonkeyBars3k/ReaScripts#146]
- parent temp unglue doesn't need to be aligned with any instance. just needs to position, crop, glue correctly
  - have to get proper position for crop though: _restored_items_position_adjustment_
- due to possibiltity of negative offset taking restored items before position 0, must detect that amount and slide forward so temp unglue happens at zero

**Comment by basicchannels** [comment]
Interesting usage of Verb form

**Comment by MonkeyBars3k** [comment]
> Interesting usage of Verb form 

common in programming parlance

**Comment by MonkeyBars3k** [comment]
1.53
