### ISSUE TITLE
Settings applied to wrong send

### ISSUE THREAD

**Issue by SchittBull** [MonkeyBars3k/ReaScripts#369]
When adding a send to a track that already has a send applied with a lower number, the send settings are applied to the send with the highest number instead of the newly created one.
[reaper_ojMPIDvjna.webm](https://github.com/MonkeyBars3k/ReaScripts/assets/53765158/d9b80836-41f5-448c-8476-36d2f7a721b4)

**Comment by MonkeyBars3k** [comment]
Thanks for your report! I was able to replicate this. NB "lower number" refers to the destination track number, so in order to replicate, the second send needs to go to a lower track number than the first

**Comment by MonkeyBars3k** [comment]
Fixed and deployed, thanks again for your report – feel free to sync and confirm fix here
