### ISSUE TITLE
The script filename has characters that prevent it from being zipped up

### ISSUE THREAD

**Issue by AtmanActive** [MonkeyBars3k/ReaScripts#370]
Hi,

Thank you for developing these great ReaScripts.

Unfortunately, there is a problem.
Your script:

[MB_Fold source media into imploded takes at item length – if multiple takes, explode active take to new track.lua](Fold Source/MB_Fold source media into imploded takes at item length – if multiple takes, explode active take to new track.lua)

has invalid characters in it's filename. 
The character is valid on windows alright, but can not be zipped up.

Try right clicking on your script on your windows machine and choose Send To -> Compressed (Zipped) folder. 
You'll get an error message: "cannot be compressed because it includes characters that cannot be used in a compressed folder, such as –. You should rename this file or directory.".

The problem is that this script now prevents me from zipping up my whole Reaper (portable) folder.
If I rename it locally, ReaPack will lose track of it and will just download it again.
Same if I delete it.
Hence, the only way out of this is for you to rename it at the source.

Just wanted to let you know.

Thanks.

**Comment by MonkeyBars3k** [comment]
Thanks for the heads up! Attempting to deploy a fix now. I don't have a Windows machine to test so please reply back

**Comment by AtmanActive** [comment]
Yup, fixed now after I did ReaPack->Synchronize Packages.
Thank you for the quick fix.
