### ISSUE TITLE
Dragging pooled item during edit moves other pooled instances

### ISSUE THREAD

**Issue by MonkeyBars3k** [MonkeyBars3k/ReaScripts#84]
Move other pooled instances only given condition that edit changed left edge audio position as well

**Comment by MonkeyBars3k** [comment]
Use GetMediaItemTakeInfo_Value to get D_STARTOFFS

**Comment by MonkeyBars3k** [comment]
Logic:
Do position update ONLY IF
- Position changed AND
- - Position delta between container and 1st item changed OR
- - Media offset of 1st item changed

Other logic?

**Comment by Phazmaonline** [comment]
The ones you proposed make sense. Another condition I could think of is:

- Position delta between container (end) and last item's media end changed

I guess this would be needed to support  extending/trimming the right edge.

**Comment by MonkeyBars3k** [comment]
> The ones you proposed make sense. Another condition I could think of is:
> 
> * Position delta between container (end) and last item's media end changed
> 
> I guess this would be needed to support extending/trimming the right edge.

This is not relevant for position changes – only length, which is currently functioning properly afaict.

**Comment by MonkeyBars3k** [comment]
I'm starting to think there is no program logic that correlates to the user experience during Reglue – it might have to be asked on Reglue any time the position has changed since last Glue.

**Comment by MonkeyBars3k** [comment]
Psychologically, editing edges makes me want to propagate, while dragging the entire group of items does not. Since there's no effective way of detecting a difference between these in code, dialog Yes/No to propagate may be best.

**Comment by MonkeyBars3k** [comment]
Example dialog text:
Container item position has changed since you started Editing it!
Do you want to propagate this position change to the rest of the pooled container items?
YES | NO

**Comment by MonkeyBars3k** [comment]
1.40
