### ISSUE TITLE
Canceling render dialog spits out error

### ISSUE THREAD

**Issue by Breeder** [MonkeyBars3k/ReaScripts#96]
Canceling render dialog will spit out error:
MB_Glue-Reversible Utils.lua:714: bad argument #1 to 'SetActiveTake' (MediaItem_Take expected)

Affected script (version 1.39)
MB_Glue-Reversible - Smart Glue or Edit selected item(s) by context, ignoring time selection

Probably because canceling the render dialog makes REAPER not create new audio item so the MediaItem_Take expected ends up as nil

edit: render dialog probably jumps up cause the project is unsaved

![presentation](https://user-images.githubusercontent.com/7748689/143150474-50d3e442-663f-4d15-b75c-60cda79d08e5.gif)

**Comment by MonkeyBars3k** [comment]
Hopefully fixed by escaping the Windows drive path backslashes

**Comment by MonkeyBars3k** [comment]
macOS bug: no render path dialog. rather Reaper just errors out. won't fix

https://forum.cockos.com/showthread.php?p=2502226#post2502226

**Comment by MonkeyBars3k** [comment]
1.51
